@apiURL = http://localhost:8080/notes

GET {{apiURL}}

###

POST {{apiURL}}
Content-Type: application/json 

{"text": "testing POST again"}

###

PATCH {{apiURL}}/1 
Content-Type: application/json

{"note": "morjens!"}

###

DELETE {{apiURL}}/1
